SELECT 
  BO_CLASSES.NAMECLASS AS NAMECLASS, 
  BO_CLASSES.NAMETABLE AS NAMETABLE, 
  BO_CLASSES.FGUID AS CLS_FGUID,
  BO_ATTR_CLASSES.NAMEATTR AS NAMEATTR, 
  BO_ATTR_CLASSES.NAMEFIELD AS NAMEFIELD, 
  BO_ATTR_CLASSES.NAMESCREEN AS NAMESCREEN
FROM BO_ATTR_CLASSES 
LEFT OUTER JOIN BO_CLASSES
ON BO_CLASSES.GUID = BO_ATTR_CLASSES.FGUID 
INNER JOIN BO_ATTR_CLASSES AS t3 
ON t3.NAMEFIELD = 'GUID' AND t3.FGUID = BO_CLASSES.GUID 
AND not t3.NAMEFIELD is NULL 
WHERE substring(BO_ATTR_CLASSES.ARRAYMDATA, 3,1) = '1' 
ORDER BY CLS_FGUID, NAMETABLE