SELECT t0.*, t3.OBJECTGUID FROM TSTEP1 AS t0
LEFT JOIN (SELECT t1.* FROM BO_ACCEPTED_LINKS AS t1
INNER JOIN BO_ACCEPTED_LINKS AS t2
ON t1.FID = t2.FID  AND t2.ID % 2 = 1 AND t1.ID % 2 = 0
AND t2.OBJECTGUID IN ('y2RZerqA8wZAM1Ggqnw4dc')
) AS t3 ON t0.GUID = t3.OBJECTGUID